//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuruPeru_ECommers.VentasServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/VENTAS")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apeClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaNacClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apeCliente {
            get {
                return this.apeClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.apeClienteField, value) != true)) {
                    this.apeClienteField = value;
                    this.RaisePropertyChanged("apeCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaNacCliente {
            get {
                return this.fechaNacClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaNacClienteField, value) != true)) {
                    this.fechaNacClienteField = value;
                    this.RaisePropertyChanged("fechaNacCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.idClienteField, value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.idUsuarioField, value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/VENTAS")]
    [System.SerializableAttribute()]
    public partial class Proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomProvField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProv {
            get {
                return this.idProvField;
            }
            set {
                if ((object.ReferenceEquals(this.idProvField, value) != true)) {
                    this.idProvField = value;
                    this.RaisePropertyChanged("idProv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomProv {
            get {
                return this.nomProvField;
            }
            set {
                if ((object.ReferenceEquals(this.nomProvField, value) != true)) {
                    this.nomProvField = value;
                    this.RaisePropertyChanged("nomProv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/VENTAS")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imgProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionProducto {
            get {
                return this.descripcionProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionProductoField, value) != true)) {
                    this.descripcionProductoField = value;
                    this.RaisePropertyChanged("descripcionProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.idProductoField, value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProveedor {
            get {
                return this.idProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.idProveedorField, value) != true)) {
                    this.idProveedorField = value;
                    this.RaisePropertyChanged("idProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imgProducto {
            get {
                return this.imgProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.imgProductoField, value) != true)) {
                    this.imgProductoField = value;
                    this.RaisePropertyChanged("imgProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precioProducto {
            get {
                return this.precioProductoField;
            }
            set {
                if ((this.precioProductoField.Equals(value) != true)) {
                    this.precioProductoField = value;
                    this.RaisePropertyChanged("precioProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stockProducto {
            get {
                return this.stockProductoField;
            }
            set {
                if ((this.stockProductoField.Equals(value) != true)) {
                    this.stockProductoField = value;
                    this.RaisePropertyChanged("stockProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tituloProducto {
            get {
                return this.tituloProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloProductoField, value) != true)) {
                    this.tituloProductoField = value;
                    this.RaisePropertyChanged("tituloProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemProducto", Namespace="http://schemas.datacontract.org/2004/07/VENTAS")]
    [System.SerializableAttribute()]
    public partial class ItemProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantidadProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidadProducto {
            get {
                return this.cantidadProductoField;
            }
            set {
                if ((this.cantidadProductoField.Equals(value) != true)) {
                    this.cantidadProductoField = value;
                    this.RaisePropertyChanged("cantidadProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.idProductoField, value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precioProducto {
            get {
                return this.precioProductoField;
            }
            set {
                if ((this.precioProductoField.Equals(value) != true)) {
                    this.precioProductoField = value;
                    this.RaisePropertyChanged("precioProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VentasServicio.Ventas")]
    public interface Ventas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ventas/ListarClientes", ReplyAction="http://tempuri.org/Ventas/ListarClientesResponse")]
        RuruPeru_ECommers.VentasServicio.Cliente[] ListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ventas/ListarClientes", ReplyAction="http://tempuri.org/Ventas/ListarClientesResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.VentasServicio.Cliente[]> ListarClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ventas/ListarProveedor", ReplyAction="http://tempuri.org/Ventas/ListarProveedorResponse")]
        RuruPeru_ECommers.VentasServicio.Proveedor[] ListarProveedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ventas/ListarProveedor", ReplyAction="http://tempuri.org/Ventas/ListarProveedorResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.VentasServicio.Proveedor[]> ListarProveedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ventas/ListarProductos", ReplyAction="http://tempuri.org/Ventas/ListarProductosResponse")]
        RuruPeru_ECommers.VentasServicio.Producto[] ListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ventas/ListarProductos", ReplyAction="http://tempuri.org/Ventas/ListarProductosResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.VentasServicio.Producto[]> ListarProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ventas/ActualizarStock", ReplyAction="http://tempuri.org/Ventas/ActualizarStockResponse")]
        string ActualizarStock(RuruPeru_ECommers.VentasServicio.ItemProducto reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ventas/ActualizarStock", ReplyAction="http://tempuri.org/Ventas/ActualizarStockResponse")]
        System.Threading.Tasks.Task<string> ActualizarStockAsync(RuruPeru_ECommers.VentasServicio.ItemProducto reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ventas/RealizarVenta", ReplyAction="http://tempuri.org/Ventas/RealizarVentaResponse")]
        string RealizarVenta(string idCliente, RuruPeru_ECommers.VentasServicio.ItemProducto[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ventas/RealizarVenta", ReplyAction="http://tempuri.org/Ventas/RealizarVentaResponse")]
        System.Threading.Tasks.Task<string> RealizarVentaAsync(string idCliente, RuruPeru_ECommers.VentasServicio.ItemProducto[] items);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VentasChannel : RuruPeru_ECommers.VentasServicio.Ventas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentasClient : System.ServiceModel.ClientBase<RuruPeru_ECommers.VentasServicio.Ventas>, RuruPeru_ECommers.VentasServicio.Ventas {
        
        public VentasClient() {
        }
        
        public VentasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RuruPeru_ECommers.VentasServicio.Cliente[] ListarClientes() {
            return base.Channel.ListarClientes();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.VentasServicio.Cliente[]> ListarClientesAsync() {
            return base.Channel.ListarClientesAsync();
        }
        
        public RuruPeru_ECommers.VentasServicio.Proveedor[] ListarProveedor() {
            return base.Channel.ListarProveedor();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.VentasServicio.Proveedor[]> ListarProveedorAsync() {
            return base.Channel.ListarProveedorAsync();
        }
        
        public RuruPeru_ECommers.VentasServicio.Producto[] ListarProductos() {
            return base.Channel.ListarProductos();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.VentasServicio.Producto[]> ListarProductosAsync() {
            return base.Channel.ListarProductosAsync();
        }
        
        public string ActualizarStock(RuruPeru_ECommers.VentasServicio.ItemProducto reg) {
            return base.Channel.ActualizarStock(reg);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarStockAsync(RuruPeru_ECommers.VentasServicio.ItemProducto reg) {
            return base.Channel.ActualizarStockAsync(reg);
        }
        
        public string RealizarVenta(string idCliente, RuruPeru_ECommers.VentasServicio.ItemProducto[] items) {
            return base.Channel.RealizarVenta(idCliente, items);
        }
        
        public System.Threading.Tasks.Task<string> RealizarVentaAsync(string idCliente, RuruPeru_ECommers.VentasServicio.ItemProducto[] items) {
            return base.Channel.RealizarVentaAsync(idCliente, items);
        }
    }
}
