//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuruPeru_ECommers.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fotoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionEstado {
            get {
                return this.descripcionEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionEstadoField, value) != true)) {
                    this.descripcionEstadoField = value;
                    this.RaisePropertyChanged("descripcionEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fotoUsuario {
            get {
                return this.fotoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoUsuarioField, value) != true)) {
                    this.fotoUsuarioField = value;
                    this.RaisePropertyChanged("fotoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.idUsuarioField, value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomDistrito {
            get {
                return this.nomDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomDistritoField, value) != true)) {
                    this.nomDistritoField = value;
                    this.RaisePropertyChanged("nomDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomUsuario {
            get {
                return this.nomUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nomUsuarioField, value) != true)) {
                    this.nomUsuarioField = value;
                    this.RaisePropertyChanged("nomUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apeClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
<<<<<<< HEAD
        private string fechaNacClienteField;
=======
        private string descripcionEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaNacClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fotoUsuarioField;
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUsuarioField;
        
<<<<<<< HEAD
=======
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomUsuarioField;
        
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apeCliente {
            get {
                return this.apeClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.apeClienteField, value) != true)) {
                    this.apeClienteField = value;
                    this.RaisePropertyChanged("apeCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
<<<<<<< HEAD
        public string fechaNacCliente {
=======
        public string descripcionEstado {
            get {
                return this.descripcionEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionEstadoField, value) != true)) {
                    this.descripcionEstadoField = value;
                    this.RaisePropertyChanged("descripcionEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNacCliente {
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
            get {
                return this.fechaNacClienteField;
            }
            set {
<<<<<<< HEAD
                if ((object.ReferenceEquals(this.fechaNacClienteField, value) != true)) {
=======
                if ((this.fechaNacClienteField.Equals(value) != true)) {
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
                    this.fechaNacClienteField = value;
                    this.RaisePropertyChanged("fechaNacCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
<<<<<<< HEAD
=======
        public string fotoUsuario {
            get {
                return this.fotoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoUsuarioField, value) != true)) {
                    this.fotoUsuarioField = value;
                    this.RaisePropertyChanged("fotoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
        public string idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.idClienteField, value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.idUsuarioField, value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
<<<<<<< HEAD
=======
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomUsuario {
            get {
                return this.nomUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nomUsuarioField, value) != true)) {
                    this.nomUsuarioField = value;
                    this.RaisePropertyChanged("nomUsuario");
                }
            }
        }
        
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class Proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
<<<<<<< HEAD
        private string idProvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomProvField;
=======
        private string descripcionProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rucProveedorField;
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
<<<<<<< HEAD
        public string idProv {
            get {
                return this.idProvField;
            }
            set {
                if ((object.ReferenceEquals(this.idProvField, value) != true)) {
                    this.idProvField = value;
                    this.RaisePropertyChanged("idProv");
=======
        public string descripcionProveedor {
            get {
                return this.descripcionProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionProveedorField, value) != true)) {
                    this.descripcionProveedorField = value;
                    this.RaisePropertyChanged("descripcionProveedor");
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
<<<<<<< HEAD
        public string nomProv {
            get {
                return this.nomProvField;
            }
            set {
                if ((object.ReferenceEquals(this.nomProvField, value) != true)) {
                    this.nomProvField = value;
                    this.RaisePropertyChanged("nomProv");
=======
        public string dniProveedor {
            get {
                return this.dniProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.dniProveedorField, value) != true)) {
                    this.dniProveedorField = value;
                    this.RaisePropertyChanged("dniProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProveedor {
            get {
                return this.idProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.idProveedorField, value) != true)) {
                    this.idProveedorField = value;
                    this.RaisePropertyChanged("idProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.idUsuarioField, value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rucProveedor {
            get {
                return this.rucProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.rucProveedorField, value) != true)) {
                    this.rucProveedorField = value;
                    this.RaisePropertyChanged("rucProveedor");
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
<<<<<<< HEAD
        private string descripcionProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaField;
=======
        private string descripcionCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionProductoField;
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imgProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
<<<<<<< HEAD
        public string descripcionProducto {
            get {
                return this.descripcionProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionProductoField, value) != true)) {
                    this.descripcionProductoField = value;
                    this.RaisePropertyChanged("descripcionProducto");
=======
        public string descripcionCategoria {
            get {
                return this.descripcionCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionCategoriaField, value) != true)) {
                    this.descripcionCategoriaField = value;
                    this.RaisePropertyChanged("descripcionCategoria");
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
<<<<<<< HEAD
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
=======
        public string descripcionProducto {
            get {
                return this.descripcionProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionProductoField, value) != true)) {
                    this.descripcionProductoField = value;
                    this.RaisePropertyChanged("descripcionProducto");
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.idProductoField, value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProveedor {
            get {
                return this.idProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.idProveedorField, value) != true)) {
                    this.idProveedorField = value;
                    this.RaisePropertyChanged("idProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imgProducto {
            get {
                return this.imgProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.imgProductoField, value) != true)) {
                    this.imgProductoField = value;
                    this.RaisePropertyChanged("imgProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precioProducto {
            get {
                return this.precioProductoField;
            }
            set {
                if ((this.precioProductoField.Equals(value) != true)) {
                    this.precioProductoField = value;
                    this.RaisePropertyChanged("precioProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stockProducto {
            get {
                return this.stockProductoField;
            }
            set {
                if ((this.stockProductoField.Equals(value) != true)) {
                    this.stockProductoField = value;
                    this.RaisePropertyChanged("stockProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tituloProducto {
            get {
                return this.tituloProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloProductoField, value) != true)) {
                    this.tituloProductoField = value;
                    this.RaisePropertyChanged("tituloProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
<<<<<<< HEAD
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemProducto", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class ItemProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
=======
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class Categoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
<<<<<<< HEAD
        private int cantidadProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioProductoField;
=======
        private string descripcionCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idCategoriaField;
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
<<<<<<< HEAD
        public int cantidadProducto {
            get {
                return this.cantidadProductoField;
            }
            set {
                if ((this.cantidadProductoField.Equals(value) != true)) {
                    this.cantidadProductoField = value;
                    this.RaisePropertyChanged("cantidadProducto");
=======
        public string descripcionCategoria {
            get {
                return this.descripcionCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionCategoriaField, value) != true)) {
                    this.descripcionCategoriaField = value;
                    this.RaisePropertyChanged("descripcionCategoria");
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
<<<<<<< HEAD
        public string idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.idProductoField, value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
=======
        public short idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
                }
            }
        }
        
<<<<<<< HEAD
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
=======
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoUsuario", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class EstadoUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idEstadoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionEstado {
            get {
                return this.descripcionEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionEstadoField, value) != true)) {
                    this.descripcionEstadoField = value;
                    this.RaisePropertyChanged("descripcionEstado");
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
<<<<<<< HEAD
        public decimal precioProducto {
            get {
                return this.precioProductoField;
            }
            set {
                if ((this.precioProductoField.Equals(value) != true)) {
                    this.precioProductoField = value;
                    this.RaisePropertyChanged("precioProducto");
=======
        public short idEstadoUsuario {
            get {
                return this.idEstadoUsuarioField;
            }
            set {
                if ((this.idEstadoUsuarioField.Equals(value) != true)) {
                    this.idEstadoUsuarioField = value;
                    this.RaisePropertyChanged("idEstadoUsuario");
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
<<<<<<< HEAD
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarClientes", ReplyAction="http://tempuri.org/IService1/ListarClientesResponse")]
        RuruPeru_ECommers.ServiceReference1.Cliente[] ListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarClientes", ReplyAction="http://tempuri.org/IService1/ListarClientesResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Cliente[]> ListarClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarProveedor", ReplyAction="http://tempuri.org/IService1/ListarProveedorResponse")]
        RuruPeru_ECommers.ServiceReference1.Proveedor[] ListarProveedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarProveedor", ReplyAction="http://tempuri.org/IService1/ListarProveedorResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Proveedor[]> ListarProveedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarProductos", ReplyAction="http://tempuri.org/IService1/ListarProductosResponse")]
        RuruPeru_ECommers.ServiceReference1.Producto[] ListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarProductos", ReplyAction="http://tempuri.org/IService1/ListarProductosResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Producto[]> ListarProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarStock", ReplyAction="http://tempuri.org/IService1/ActualizarStockResponse")]
        string ActualizarStock(RuruPeru_ECommers.ServiceReference1.ItemProducto reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarStock", ReplyAction="http://tempuri.org/IService1/ActualizarStockResponse")]
        System.Threading.Tasks.Task<string> ActualizarStockAsync(RuruPeru_ECommers.ServiceReference1.ItemProducto reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RealizarVenta", ReplyAction="http://tempuri.org/IService1/RealizarVentaResponse")]
        string RealizarVenta(string idCliente, RuruPeru_ECommers.ServiceReference1.ItemProducto[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RealizarVenta", ReplyAction="http://tempuri.org/IService1/RealizarVentaResponse")]
        System.Threading.Tasks.Task<string> RealizarVentaAsync(string idCliente, RuruPeru_ECommers.ServiceReference1.ItemProducto[] items);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : RuruPeru_ECommers.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
=======
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Consulta")]
    public interface Consulta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarUsuarios", ReplyAction="http://tempuri.org/Consulta/ListarUsuariosResponse")]
        RuruPeru_ECommers.ServiceReference1.Usuario[] ListarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarUsuarios", ReplyAction="http://tempuri.org/Consulta/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Usuario[]> ListarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarClientes", ReplyAction="http://tempuri.org/Consulta/ListarClientesResponse")]
        RuruPeru_ECommers.ServiceReference1.Cliente[] ListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarClientes", ReplyAction="http://tempuri.org/Consulta/ListarClientesResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Cliente[]> ListarClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarProveedor", ReplyAction="http://tempuri.org/Consulta/ListarProveedorResponse")]
        RuruPeru_ECommers.ServiceReference1.Proveedor[] ListarProveedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarProveedor", ReplyAction="http://tempuri.org/Consulta/ListarProveedorResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Proveedor[]> ListarProveedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarProductos", ReplyAction="http://tempuri.org/Consulta/ListarProductosResponse")]
        RuruPeru_ECommers.ServiceReference1.Producto[] ListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarProductos", ReplyAction="http://tempuri.org/Consulta/ListarProductosResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Producto[]> ListarProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListaCategoriaProd", ReplyAction="http://tempuri.org/Consulta/ListaCategoriaProdResponse")]
        RuruPeru_ECommers.ServiceReference1.Categoria[] ListaCategoriaProd();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListaCategoriaProd", ReplyAction="http://tempuri.org/Consulta/ListaCategoriaProdResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Categoria[]> ListaCategoriaProdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarEstadoUsuario", ReplyAction="http://tempuri.org/Consulta/ListarEstadoUsuarioResponse")]
        RuruPeru_ECommers.ServiceReference1.EstadoUsuario[] ListarEstadoUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarEstadoUsuario", ReplyAction="http://tempuri.org/Consulta/ListarEstadoUsuarioResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.EstadoUsuario[]> ListarEstadoUsuarioAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaChannel : RuruPeru_ECommers.ServiceReference1.Consulta, System.ServiceModel.IClientChannel {
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
<<<<<<< HEAD
    public partial class Service1Client : System.ServiceModel.ClientBase<RuruPeru_ECommers.ServiceReference1.IService1>, RuruPeru_ECommers.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
=======
    public partial class ConsultaClient : System.ServiceModel.ClientBase<RuruPeru_ECommers.ServiceReference1.Consulta>, RuruPeru_ECommers.ServiceReference1.Consulta {
        
        public ConsultaClient() {
        }
        
        public ConsultaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RuruPeru_ECommers.ServiceReference1.Usuario[] ListarUsuarios() {
            return base.Channel.ListarUsuarios();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Usuario[]> ListarUsuariosAsync() {
            return base.Channel.ListarUsuariosAsync();
        }
        
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
        public RuruPeru_ECommers.ServiceReference1.Cliente[] ListarClientes() {
            return base.Channel.ListarClientes();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Cliente[]> ListarClientesAsync() {
            return base.Channel.ListarClientesAsync();
        }
        
        public RuruPeru_ECommers.ServiceReference1.Proveedor[] ListarProveedor() {
            return base.Channel.ListarProveedor();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Proveedor[]> ListarProveedorAsync() {
            return base.Channel.ListarProveedorAsync();
        }
        
        public RuruPeru_ECommers.ServiceReference1.Producto[] ListarProductos() {
            return base.Channel.ListarProductos();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Producto[]> ListarProductosAsync() {
            return base.Channel.ListarProductosAsync();
        }
        
<<<<<<< HEAD
        public string ActualizarStock(RuruPeru_ECommers.ServiceReference1.ItemProducto reg) {
            return base.Channel.ActualizarStock(reg);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarStockAsync(RuruPeru_ECommers.ServiceReference1.ItemProducto reg) {
            return base.Channel.ActualizarStockAsync(reg);
        }
        
        public string RealizarVenta(string idCliente, RuruPeru_ECommers.ServiceReference1.ItemProducto[] items) {
            return base.Channel.RealizarVenta(idCliente, items);
        }
        
        public System.Threading.Tasks.Task<string> RealizarVentaAsync(string idCliente, RuruPeru_ECommers.ServiceReference1.ItemProducto[] items) {
            return base.Channel.RealizarVentaAsync(idCliente, items);
=======
        public RuruPeru_ECommers.ServiceReference1.Categoria[] ListaCategoriaProd() {
            return base.Channel.ListaCategoriaProd();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.Categoria[]> ListaCategoriaProdAsync() {
            return base.Channel.ListaCategoriaProdAsync();
        }
        
        public RuruPeru_ECommers.ServiceReference1.EstadoUsuario[] ListarEstadoUsuario() {
            return base.Channel.ListarEstadoUsuario();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.ServiceReference1.EstadoUsuario[]> ListarEstadoUsuarioAsync() {
            return base.Channel.ListarEstadoUsuarioAsync();
>>>>>>> b8d3d8b664242b32ac9093c9c1a4653e2ad1fa6d
        }
    }
}
