//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuruPeru_ECommers.ConsultaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fotoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionEstado {
            get {
                return this.descripcionEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionEstadoField, value) != true)) {
                    this.descripcionEstadoField = value;
                    this.RaisePropertyChanged("descripcionEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fotoUsuario {
            get {
                return this.fotoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoUsuarioField, value) != true)) {
                    this.fotoUsuarioField = value;
                    this.RaisePropertyChanged("fotoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.idUsuarioField, value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomDistrito {
            get {
                return this.nomDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomDistritoField, value) != true)) {
                    this.nomDistritoField = value;
                    this.RaisePropertyChanged("nomDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomUsuario {
            get {
                return this.nomUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nomUsuarioField, value) != true)) {
                    this.nomUsuarioField = value;
                    this.RaisePropertyChanged("nomUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apeClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaNacClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fotoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apeCliente {
            get {
                return this.apeClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.apeClienteField, value) != true)) {
                    this.apeClienteField = value;
                    this.RaisePropertyChanged("apeCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionEstado {
            get {
                return this.descripcionEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionEstadoField, value) != true)) {
                    this.descripcionEstadoField = value;
                    this.RaisePropertyChanged("descripcionEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNacCliente {
            get {
                return this.fechaNacClienteField;
            }
            set {
                if ((this.fechaNacClienteField.Equals(value) != true)) {
                    this.fechaNacClienteField = value;
                    this.RaisePropertyChanged("fechaNacCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fotoUsuario {
            get {
                return this.fotoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoUsuarioField, value) != true)) {
                    this.fotoUsuarioField = value;
                    this.RaisePropertyChanged("fotoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.idClienteField, value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.idUsuarioField, value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomUsuario {
            get {
                return this.nomUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nomUsuarioField, value) != true)) {
                    this.nomUsuarioField = value;
                    this.RaisePropertyChanged("nomUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class Proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rucProveedorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionProveedor {
            get {
                return this.descripcionProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionProveedorField, value) != true)) {
                    this.descripcionProveedorField = value;
                    this.RaisePropertyChanged("descripcionProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dniProveedor {
            get {
                return this.dniProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.dniProveedorField, value) != true)) {
                    this.dniProveedorField = value;
                    this.RaisePropertyChanged("dniProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProveedor {
            get {
                return this.idProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.idProveedorField, value) != true)) {
                    this.idProveedorField = value;
                    this.RaisePropertyChanged("idProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.idUsuarioField, value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rucProveedor {
            get {
                return this.rucProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.rucProveedorField, value) != true)) {
                    this.rucProveedorField = value;
                    this.RaisePropertyChanged("rucProveedor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imgProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionCategoria {
            get {
                return this.descripcionCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionCategoriaField, value) != true)) {
                    this.descripcionCategoriaField = value;
                    this.RaisePropertyChanged("descripcionCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionProducto {
            get {
                return this.descripcionProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionProductoField, value) != true)) {
                    this.descripcionProductoField = value;
                    this.RaisePropertyChanged("descripcionProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.idProductoField, value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProveedor {
            get {
                return this.idProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.idProveedorField, value) != true)) {
                    this.idProveedorField = value;
                    this.RaisePropertyChanged("idProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imgProducto {
            get {
                return this.imgProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.imgProductoField, value) != true)) {
                    this.imgProductoField = value;
                    this.RaisePropertyChanged("imgProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precioProducto {
            get {
                return this.precioProductoField;
            }
            set {
                if ((this.precioProductoField.Equals(value) != true)) {
                    this.precioProductoField = value;
                    this.RaisePropertyChanged("precioProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stockProducto {
            get {
                return this.stockProductoField;
            }
            set {
                if ((this.stockProductoField.Equals(value) != true)) {
                    this.stockProductoField = value;
                    this.RaisePropertyChanged("stockProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tituloProducto {
            get {
                return this.tituloProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloProductoField, value) != true)) {
                    this.tituloProductoField = value;
                    this.RaisePropertyChanged("tituloProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class Categoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idCategoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionCategoria {
            get {
                return this.descripcionCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionCategoriaField, value) != true)) {
                    this.descripcionCategoriaField = value;
                    this.RaisePropertyChanged("descripcionCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoUsuario", Namespace="http://schemas.datacontract.org/2004/07/CONSULTA")]
    [System.SerializableAttribute()]
    public partial class EstadoUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idEstadoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionEstado {
            get {
                return this.descripcionEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionEstadoField, value) != true)) {
                    this.descripcionEstadoField = value;
                    this.RaisePropertyChanged("descripcionEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short idEstadoUsuario {
            get {
                return this.idEstadoUsuarioField;
            }
            set {
                if ((this.idEstadoUsuarioField.Equals(value) != true)) {
                    this.idEstadoUsuarioField = value;
                    this.RaisePropertyChanged("idEstadoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsultaServicio.Consulta")]
    public interface Consulta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarUsuarios", ReplyAction="http://tempuri.org/Consulta/ListarUsuariosResponse")]
        RuruPeru_ECommers.ConsultaServicio.Usuario[] ListarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarUsuarios", ReplyAction="http://tempuri.org/Consulta/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ConsultaServicio.Usuario[]> ListarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarClientes", ReplyAction="http://tempuri.org/Consulta/ListarClientesResponse")]
        RuruPeru_ECommers.ConsultaServicio.Cliente[] ListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarClientes", ReplyAction="http://tempuri.org/Consulta/ListarClientesResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ConsultaServicio.Cliente[]> ListarClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarProveedor", ReplyAction="http://tempuri.org/Consulta/ListarProveedorResponse")]
        RuruPeru_ECommers.ConsultaServicio.Proveedor[] ListarProveedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarProveedor", ReplyAction="http://tempuri.org/Consulta/ListarProveedorResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ConsultaServicio.Proveedor[]> ListarProveedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarProductos", ReplyAction="http://tempuri.org/Consulta/ListarProductosResponse")]
        RuruPeru_ECommers.ConsultaServicio.Producto[] ListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarProductos", ReplyAction="http://tempuri.org/Consulta/ListarProductosResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ConsultaServicio.Producto[]> ListarProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListaCategoriaProd", ReplyAction="http://tempuri.org/Consulta/ListaCategoriaProdResponse")]
        RuruPeru_ECommers.ConsultaServicio.Categoria[] ListaCategoriaProd();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListaCategoriaProd", ReplyAction="http://tempuri.org/Consulta/ListaCategoriaProdResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ConsultaServicio.Categoria[]> ListaCategoriaProdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarEstadoUsuario", ReplyAction="http://tempuri.org/Consulta/ListarEstadoUsuarioResponse")]
        RuruPeru_ECommers.ConsultaServicio.EstadoUsuario[] ListarEstadoUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta/ListarEstadoUsuario", ReplyAction="http://tempuri.org/Consulta/ListarEstadoUsuarioResponse")]
        System.Threading.Tasks.Task<RuruPeru_ECommers.ConsultaServicio.EstadoUsuario[]> ListarEstadoUsuarioAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaChannel : RuruPeru_ECommers.ConsultaServicio.Consulta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaClient : System.ServiceModel.ClientBase<RuruPeru_ECommers.ConsultaServicio.Consulta>, RuruPeru_ECommers.ConsultaServicio.Consulta {
        
        public ConsultaClient() {
        }
        
        public ConsultaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RuruPeru_ECommers.ConsultaServicio.Usuario[] ListarUsuarios() {
            return base.Channel.ListarUsuarios();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.ConsultaServicio.Usuario[]> ListarUsuariosAsync() {
            return base.Channel.ListarUsuariosAsync();
        }
        
        public RuruPeru_ECommers.ConsultaServicio.Cliente[] ListarClientes() {
            return base.Channel.ListarClientes();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.ConsultaServicio.Cliente[]> ListarClientesAsync() {
            return base.Channel.ListarClientesAsync();
        }
        
        public RuruPeru_ECommers.ConsultaServicio.Proveedor[] ListarProveedor() {
            return base.Channel.ListarProveedor();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.ConsultaServicio.Proveedor[]> ListarProveedorAsync() {
            return base.Channel.ListarProveedorAsync();
        }
        
        public RuruPeru_ECommers.ConsultaServicio.Producto[] ListarProductos() {
            return base.Channel.ListarProductos();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.ConsultaServicio.Producto[]> ListarProductosAsync() {
            return base.Channel.ListarProductosAsync();
        }
        
        public RuruPeru_ECommers.ConsultaServicio.Categoria[] ListaCategoriaProd() {
            return base.Channel.ListaCategoriaProd();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.ConsultaServicio.Categoria[]> ListaCategoriaProdAsync() {
            return base.Channel.ListaCategoriaProdAsync();
        }
        
        public RuruPeru_ECommers.ConsultaServicio.EstadoUsuario[] ListarEstadoUsuario() {
            return base.Channel.ListarEstadoUsuario();
        }
        
        public System.Threading.Tasks.Task<RuruPeru_ECommers.ConsultaServicio.EstadoUsuario[]> ListarEstadoUsuarioAsync() {
            return base.Channel.ListarEstadoUsuarioAsync();
        }
    }
}
